# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = My_browser

QT += core gui widgets printsupport webchannel webengine webenginewidgets




include(My_browser.pri)
